version: '3'
services:
  nginx: 
    image: sscraping-http
    container_name: own
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/mysite.template
      - ./ssl:/etc/nginx/ssl
    environment:
      - WWW_URL=192.168.99.100
      - HTTP_SERVER_NAME=docker.tld
      - CERT_NAME=server
      - CERT_TRUST_NAME=letsencrypt
      - DH_NAME=dhparam
    command: /bin/bash -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/mysite.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"